config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeonaidLee</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <ul id="dropdown1" class="dropdown-content">
      <li><a href="#!">Profile</a></li>
      <li><a href="#!">My Courses</a></li>
      <li class="divider"></li>
      <li><a href="#!">Log Out</a></li>
    </ul>

    <ul id="dropdown2" class="dropdown-content">
      <li><a href="#!">Profile</a></li>
      <li><a href="#!">My Courses</a></li>
      <li class="divider"></li>
      <li><a href="#!">Log Out</a></li>
    </ul>

    <header>
      <nav class = "blue lighten-2 z-depth-2">
        <div class="container">
          <div class="nav-wrapper">
            <a href="#!" class="brand-logo">Seonaid Lee</a>
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
              <li><a href="#">Hire Me</a></li>
              <li><a href="#">Products</a></li>
              <li><a href="#">Sign Up</a></li>
              <li><a href="#">Log In</a></li>
               <!-- Dropdown Trigger -->
              <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">UserName<i class="material-icons right">arrow_drop_down</i></a></li>

            </ul>
          </div>
        </div>
      </nav>

      <ul class="sidenav" id="mobile-demo">
        <li><a href="#">Hire Me</a></li>
        <li><a href="#">Products</a></li>
        <li><a href="#">Sign Up</a></li>
        <li><a href="#">Log In</a></li>
          <!-- Dropdown Trigger -->
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">UserName<i class="material-icons right">arrow_drop_down</i></a></li>
      </ul>
    </header>

    <main>
      <div class="container">
        <%= yield %>
      </div>
      
    </main>

    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Seonaid Lee</h5>
            <p class="grey-text text-lighten-4">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Social</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Instagram</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Twittter</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Linked In</a></li>
            </ul>
          </div>
        </div>
        </div>
        <div class="footer-copyright">
        <div class="container">
        © 2018 Seonaid Lee
        <%= link_to "About ", pages_about_path, :class => "grey-text text-lighten-4 right" %>
       
        </div>
      </div>
    </footer>


  </body>

  <script>
    $(document).ready(function(){
      $(".sidenav").sidenav();
      $(".dropdown-trigger").dropdown();
    });
  </script>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<div class="row">
    <div class="col m6">
      <div class="card">
        <div class="card-image">
          <%= image_tag "coffee-notes.jpg" %>
          <span class="card-title">Card Title</span>
        </div>
        <div class="card-content">
          <p>I will say something fascinating patchwork living and lifestyle design for the profoundly weird.</p>
        </div>
        <div class="card-action">
          <a href="#">This is a link</a>
        </div>
      </div>
    </div>

    <div class="col m6">
      <div class="card">
        <div class="card-image">
          <%= image_tag "ArtQuote.jpg" %>
          <span class="card-title">Another Card</span>
        </div>
        <div class="card-content">
          <p>More Witty Content goes here.</p>
        </div>
        <div class="card-action">
          <a href="#">This is a link</a>
        </div>
      </div>
    </div>


    </div>
  </div>